using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System;

/**
 * this script saves the player highscores in PlayerPrefs
 * this is a file generated by unity and holds all of the player preferences
 */

public class HighScore : MonoBehaviour 
{
	 
	public Text HighScoreLabel;

	private void Awake(){
		MainMenu.HighScore[0] = PlayerPrefs.GetInt("HS1");
		MainMenu.HighScore[1] = PlayerPrefs.GetInt("HS2");
		MainMenu.HighScore[2] = PlayerPrefs.GetInt("HS3");
		MainMenu.HighScore[3] = PlayerPrefs.GetInt("HS4");
		MainMenu.HighScore[4] = PlayerPrefs.GetInt("HS5");
		MainMenu.HighScore[5] = PlayerPrefs.GetInt("HS6");
		MainMenu.HighScore[6] = PlayerPrefs.GetInt("HS7");
		MainMenu.HighScore[7] = PlayerPrefs.GetInt("HS8");
		MainMenu.HighScore[8] = PlayerPrefs.GetInt("HS9");
		MainMenu.HighScore[9] = PlayerPrefs.GetInt("HS10");
		Array.Sort (MainMenu.HighScore);

		HighScoreLabel.text = " 1: " + MainMenu.HighScore[9]+"\n 2: " + MainMenu.HighScore[8]+"\n 3: " + MainMenu.HighScore[7]+
			 "\n 4: " + MainMenu.HighScore[6]+"\n 5: " + MainMenu.HighScore[5]+"\n 6: " + MainMenu.HighScore[4]+
			"\n 7: " + MainMenu.HighScore[3]+"\n 8: " + MainMenu.HighScore[2]+"\n 9: " + MainMenu.HighScore[1]+"\n10: " + MainMenu.HighScore[0];

	}
}
